# It is recommended to load these from environment variables for security
# For example: os.getenv("ALPHA_VANTAGE_API_KEY")

# --- Data Source API Keys ---
ALPHA_VANTAGE_API_KEY = "YOUR_ALPHA_VANTAGE_API_KEY"
FRED_API_KEY = "YOUR_FRED_API_KEY"
NEWS_API_KEY = "YOUR_NEWS_API_KEY"

# --- GCP and Vertex AI Configuration ---
GCP_PROJECT_ID = "YOUR_GCP_PROJECT_ID"
GCP_REGION = "us-central1"
VECTOR_SEARCH_INDEX_ID = "YOUR_VECTOR_SEARCH_INDEX_ID"
VECTOR_SEARCH_ENDPOINT_ID = "YOUR_VECTOR_SEARCH_ENDPOINT_ID"
VECTOR_SEARCH_DEPLOYED_INDEX_ID = "YOUR_VECTOR_SEARCH_DEPLOYED_INDEX_ID"
EMBEDDING_MODEL_NAME = "textembedding-gecko@003"
